use_frameworks!

platform :ios, '8.0'

target 'XVIEWScanCodeManager_Example' do
  pod 'XVIEWScanCodeManager', :path => '../'

  target 'XVIEWScanCodeManager_Tests' do
    inherit! :search_paths

    
  end
end
